/**
 * Run before production builds used for JewelleryApp.exe / distribution ZIP.
 * - Clears CRA/webpack cache and prior build output
 * - Writes a unique build stamp so the packaged app can clear browser storage once per release
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function rmQuiet(p) {
  try {
    if (fs.existsSync(p)) {
      fs.rmSync(p, { recursive: true, force: true });
      console.log(`prebuild-dist: removed ${path.relative(root, p)}`);
    }
  } catch (e) {
    console.warn(`prebuild-dist: could not remove ${p}:`, e.message);
  }
}

// Webpack / babel / eslint caches (fresh compile)
rmQuiet(path.join(root, 'node_modules', '.cache'));
rmQuiet(path.join(root, 'build'));

const eslintCache = path.join(root, '.eslintcache');
if (fs.existsSync(eslintCache)) {
  try {
    fs.unlinkSync(eslintCache);
    console.log('prebuild-dist: removed .eslintcache');
  } catch (e) {
    console.warn('prebuild-dist: could not remove .eslintcache:', e.message);
  }
}

const genDir = path.join(root, 'src', 'generated');
if (!fs.existsSync(genDir)) {
  fs.mkdirSync(genDir, { recursive: true });
}

const stamp = new Date().toISOString();
const buildStampPath = path.join(genDir, 'buildStamp.ts');
const content = `/* eslint-disable */
/** Auto-generated by scripts/prebuild-dist.js — do not edit. */
export const DISTRIBUTION_BUILD_STAMP = ${JSON.stringify(stamp)};
`;
fs.writeFileSync(buildStampPath, content, 'utf8');
console.log('prebuild-dist: wrote src/generated/buildStamp.ts');
